language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
#  - pypy3
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 3.8-dev
      dist: xenial
      sudo: true
      env:
        - PYLINT_DISABLED=1
install:
  - pip install pip --upgrade
  - pip install -e .[dev,test] --upgrade
  - pip install pytest --upgrade
  - pip install coveralls
  - pytest --version
script:
  - if [[ -z $PYLINT_DISABLED ]]; then pylint guessit; fi
  - coverage run --source=guessit setup.py test
  - python setup.py build
after_success:
  - coveralls
