language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
install:
  - pip install pip --upgrade
  - pip install -e .[dev,test]
  - pip install pytest --upgrade
  - pip install coveralls
script:
  - if [ $TRAVIS_PYTHON_VERSION != 2.6 ]; then pylint guessit; fi
  - coverage run --source=guessit setup.py test
  - python setup.py build
after_success:
  - coveralls
